### ISSUE TITLE
Google-style functions using "Args:" are inherited with "Parameters:"

### ISSUE THREAD

**Issue by gappleto97** [meowklaski/custom_inherit#12]
This is a minor quibble, but I thought it would be good to note.

**Comment by meowklaski** [comment]
Yeah, that was actually intentional - I decided to abide by the [napoleon specification](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html#id1), which considers Args and Arguments to be aliases of Parameters. I map all aliases in this way

**Comment by gappleto97** [comment]
Okay, just wanted to be sure. Thank you.
