### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by daniel-edler** [meowklaski/custom_inherit#15]
I was copy'n'pasting the examples and found some mistakes:
* the colons are sometimes missing:
  - ``class Parent(metaclass=DocInheritMeta(style="numpy"))``should be ``class Parent(metaclass=DocInheritMeta(style="numpy")):``
  - ``class Parent(object)`` as well

The indentation is not always correct:
* the line with ``raise NotImplementedError`` to the left
* the indentations are inconsistent (but valid) in the section inheriting Docstrings using a decorator

**Comment by meowklaski** [comment]
Great! Thanks for the note. I'll fix these this evening

**Comment by meowklaski** [comment]
Finally got around to fixing it :P
